### PR TITLE
feat: add `blockNumber` to `Subquery` interface

### PR DESCRIPTION
**Pull request by jonathanpwang**

### CODE REVIEW

**Review by nyunyunyunyu — APPROVED** [review]

**Comment by ytham** [comment]
@jonathanpwang do we still want this change? tests are failing

**Comment by jonathanpwang** [comment]
> @jonathanpwang do we still want this change? tests are failing

It's a nice to have, you can cherry-pick it to the current `develop`.

**Comment by ytham** [comment]
i don't think we can cherry pick it because it's causing the tests to fail

**Comment by jonathanpwang** [comment]
can you figure out why it's failing?

**Comment by ytham** [comment]
ya let me look into it

**Comment by ytham** [comment]
@jonathanpwang I've gone ahead and gotten the tests working

**Review by jonathanpwang — COMMENTED** [review]
Thanks

**Pull request merged**
